package com.gpb.jdata.orda.mapper;

import java.util.Map;

public class TypeMapper {
    
    private static final Map<String, String> _SOURCE_TYPE_TO_OM_TYPE = Map.ofEntries(
            Map.entry("ARRAY", "ARRAY"),
            Map.entry("BIGINT", "BIGINT"),
            Map.entry("BIGNUMERIC", "NUMERIC"),
            Map.entry("BIGSERIAL", "BIGINT"),
            Map.entry("BINARY", "BINARY"),
            Map.entry("BIT", "INT"),
            Map.entry("BLOB", "BLOB"),
            Map.entry("BOOL", "BOOLEAN"),
            Map.entry("BOOLEAN", "BOOLEAN"),
            Map.entry("BPCHAR", "CHAR"),
            Map.entry("BYTEINT", "BYTEINT"),
            Map.entry("BYTES", "BYTES"),
            Map.entry("CHAR", "CHAR"),
            Map.entry("CHARACTER VARYING", "VARCHAR"),
            Map.entry("BINARY VARYING", "VARBINARY"),
            Map.entry("CURSOR", "BINARY"),
            Map.entry("DATE", "DATE"),
            Map.entry("DATETIME", "DATETIME"),
            Map.entry("DATETIME2", "DATETIME"),
            Map.entry("DATETIMEOFFSET", "DATETIME"),
            Map.entry("DECIMAL", "DECIMAL"),
            Map.entry("DOUBLE PRECISION", "DOUBLE"),
            Map.entry("DOUBLE", "DOUBLE"),
            Map.entry("ENUM", "ENUM"),
            Map.entry("FLOAT", "FLOAT"),
            Map.entry("FLOAT4", "FLOAT"),
            Map.entry("FLOAT32", "FLOAT"),
            Map.entry("FLOAT64", "DOUBLE"),
            Map.entry("FLOAT8", "DOUBLE"),
            Map.entry("GEOGRAPHY", "GEOGRAPHY"),
            Map.entry("GEOMETRY", "GEOMETRY"),
            Map.entry("HYPERLOGLOG", "BINARY"),
            Map.entry("IMAGE", "IMAGE"),
            Map.entry("INT", "INT"),
            Map.entry("INT2", "SMALLINT"),
            Map.entry("INT4", "INT"),
            Map.entry("INT8", "BIGINT"),
            Map.entry("INT16", "BIGINT"),
            Map.entry("TUPLE", "TUPLE"),
            Map.entry("SPATIAL", "SPATIAL"),
            Map.entry("INT32", "BIGINT"),
            Map.entry("INT64", "BIGINT"),
            Map.entry("INT128", "BIGINT"),
            Map.entry("INT256", "BIGINT"),
            Map.entry("INTEGER", "INT"),
            Map.entry("UINT", "INT"),
            Map.entry("UINT2", "SMALLINT"),
            Map.entry("UINT4", "INT"),
            Map.entry("UINT8", "BIGINT"),
            Map.entry("UINT16", "BIGINT"),
            Map.entry("UINT32", "BIGINT"),
            Map.entry("UINT64", "BIGINT"),
            Map.entry("UINT128", "BIGINT"),
            Map.entry("INTERVAL DAY TO SECOND", "INTERVAL"),
            Map.entry("INTERVAL YEAR TO MONTH", "INTERVAL"),
            Map.entry("INTERVAL", "INTERVAL"),
            Map.entry("LONG RAW", "BINARY"),
            Map.entry("LONG VARCHAR", "VARCHAR"),
            Map.entry("LONGBLOB", "LONGBLOB"),
            Map.entry("MAP", "MAP"),
            Map.entry("MEDIUMBLOB", "MEDIUMBLOB"),
            Map.entry("MEDIUMINT", "INT"),
            Map.entry("MEDIUMTEXT", "MEDIUMTEXT"),
            Map.entry("MONEY", "NUMBER"),
            Map.entry("NCHAR", "CHAR"),
            Map.entry("NTEXT", "NTEXT"),
            Map.entry("NULL", "NULL"),
            Map.entry("NUMBER", "NUMBER"),
            Map.entry("NUMERIC", "NUMERIC"),
            Map.entry("NVARCHAR", "VARCHAR"),
            Map.entry("OBJECT", "JSON"),
            Map.entry("RAW", "BINARY"),
            Map.entry("REAL", "FLOAT"),
            Map.entry("RECORD", "STRUCT"),
            Map.entry("ROWID", "VARCHAR"),
            Map.entry("ROWVERSION", "NUMBER"),
            Map.entry("SET", "SET"),
            Map.entry("SMALLDATETIME", "DATETIME"),
            Map.entry("SMALLINT", "SMALLINT"),
            Map.entry("SMALLMONEY", "NUMBER"),
            Map.entry("SMALLSERIAL", "SMALLINT"),
            Map.entry("SQL VARIANT", "VARBINARY"),
            Map.entry("STRING", "STRING"),
            Map.entry("STRUCT", "STRUCT"),
            Map.entry("ROW", "STRUCT"),
            Map.entry("TABLE", "BINARY"),
            Map.entry("TEXT", "TEXT"),
            Map.entry("TIME", "TIME"),
            Map.entry("TIMESTAMP WITHOUT TIME ZONE", "TIMESTAMP"),
            Map.entry("TIMESTAMP WITH TIME ZONE", "TIMESTAMP"),
            Map.entry("TIME WITH TIME ZONE", "TIME"),
            Map.entry("TIME WITHOUT TIME ZONE", "TIME"),
            Map.entry("TIMESTAMP", "TIMESTAMP"),
            Map.entry("TIMESTAMPTZ", "TIMESTAMP"),
            Map.entry("TIMESTAMP NTZ", "TIMESTAMP"),
            Map.entry("TIMESTAMP LTZ", "TIMESTAMP"),
            Map.entry("TIMESTAMP TZ", "TIMESTAMP"),
            Map.entry("TIMETZ", "TIMESTAMP"),
            Map.entry("TINYINT", "TINYINT"),
            Map.entry("UNION", "UNION"),
            Map.entry("UROWID", "VARCHAR"),
            Map.entry("VARBINARY", "VARBINARY"),
            Map.entry("VARCHAR", "VARCHAR"),
            Map.entry("VARIANT", "JSON"),
            Map.entry("JSON", "JSON"),
            Map.entry("JSONB", "JSON"),
            Map.entry("UUID", "UUID"),
            Map.entry("POINT", "GEOMETRY"),
            Map.entry("POLYGON", "GEOMETRY"),
            Map.entry("AggregateFunction()", "AGGREGATEFUNCTION"),
            Map.entry("IPV4", "IPV4"),
            Map.entry("IPV6", "IPV6"),
            Map.entry("VOID", "NULL"),
            Map.entry("TINYBLOB", "BLOB"),
            Map.entry("LONGTEXT", "TEXT"),
            Map.entry("TINYTEXT", "TEXT"),
            Map.entry("YEAR", "YEAR"),
            Map.entry("EMPTY", "NULL"),
            Map.entry("I2", "INT"),
            Map.entry("I4", "INT"),
            Map.entry("R4", "FLOAT"),
            Map.entry("R8", "DOUBLE"),
            Map.entry("CY", "NUMERIC"),
            Map.entry("BSTR", "BINARY"),
            Map.entry("IDISPATCH", "BINARY"),
            Map.entry("ERROR", "VARCHAR"),
            Map.entry("IUNKNOWN", "UNKNOWN"),
            Map.entry("UI1", "INT"),
            Map.entry("BYREF", "BINARY"),
            Map.entry("I1", "INT"),
            Map.entry("UI2", "SMALLINT"),
            Map.entry("UI4", "INT"),
            Map.entry("I8", "BIGINT"),
            Map.entry("UI8", "BIGINT"),
            Map.entry("GUID", "BINARY"),
            Map.entry("VECTOR", "BINARY"),
            Map.entry("FILETIME", "BINARY"),
            Map.entry("RESERVED", "BINARY"),
            Map.entry("STR", "STRING"),
            Map.entry("WSTR", "STRING"),
            Map.entry("UDT", "JSON"),
            Map.entry("DBDATE", "DATE"),
            Map.entry("DBTIME", "TIME"),
            Map.entry("DBTIMESTAMP", "TIMESTAMP"),
            Map.entry("HCHAPTER", "VARCHAR"),
            Map.entry("PROPVARIANT", "BINARY"),
            Map.entry("VARNUMERIC", "NUMERIC"),
            Map.entry("WDC INT", "INT"),
            Map.entry("WDC FLOAT", "FLOAT"),
            Map.entry("WDC STRING", "STRING"),
            Map.entry("WDC DATETIME", "DATETIME"),
            Map.entry("WDC BOOL", "BOOLEAN"),
            Map.entry("WDC DATE", "DATE"),
            Map.entry("WDC GEOMETRY", "GEOMETRY")
    );

    public static String mapToOrdaType(String sourceType) {
        if (sourceType != null) {
            String formattedSourceType = sourceType.toUpperCase().replace("_", " ");
            return _SOURCE_TYPE_TO_OM_TYPE.getOrDefault(formattedSourceType, "UNKNOWN");
        } else {
            return "UNKNOWN";
        }
        
    }

    public static Map<String, String> getAllTypeMappings() {
        return _SOURCE_TYPE_TO_OM_TYPE;
    }
}
