CREATE SCHEMA IF NOT EXISTS jdata;

CREATE TABLE IF NOT EXISTS jdata.actions_rep (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"timestamp" timestamp(6) NOT NULL,
	entity_name varchar(50) NOT NULL,
	additional_info text NULL,
	details text NULL,
	operation_type varchar(255) NOT NULL,
	CONSTRAINT actions_rep_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS jdata.pg_attrdef_rep (
	adnum int8 NOT NULL,
	adrelid int8 NOT NULL,
	adbin varchar(10000000) NULL,
	db varchar(255) NULL,
	CONSTRAINT pg_attrdef_rep_pkey PRIMARY KEY (adnum, adrelid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_attrdef_rep (
	adnum int8 NOT NULL,
	adrelid int8 NOT NULL,
	adbin varchar(10000000) NULL,
	db varchar(255) NULL,
	CONSTRAINT pg_attrdef_rep_pkey PRIMARY KEY (adnum, adrelid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_attribute_rep (
	atthasdef bool NULL,
	attnotnull bool NULL,
	atttypmod int4 NULL,
	attnum int8 NULL,
	attrelid int8 NOT NULL,
	atttypid int8 NULL,
	attname varchar(255) NOT NULL,
	db varchar(255) NULL,
	CONSTRAINT pg_attribute_rep_pkey PRIMARY KEY (attrelid, attname)
);

CREATE TABLE IF NOT EXISTS jdata.pg_class_rep (
	relnamespace numeric(38) NULL,
	"oid" int8 NOT NULL,
	relkind varchar(255) NULL,
	relname varchar(255) NULL,
	CONSTRAINT pg_class_rep_pkey PRIMARY KEY (oid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_constraint_rep (
	confrelid int8 NULL,
	connamespace int8 NULL,
	conrelid int8 NULL,
	contypid int8 NULL,
	"oid" int8 NOT NULL,
	conname varchar(255) NULL,
	contype varchar(255) NULL,
	db varchar(255) NULL,
	confkey _int4 NULL,
	conkey _int4 NULL,
	CONSTRAINT pg_constraint_rep_pkey PRIMARY KEY (oid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_database_rep (
	"oid" int8 NOT NULL,
	datname varchar(255) NULL,
	db varchar(255) NULL,
	CONSTRAINT pg_database_rep_pkey PRIMARY KEY (oid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_description_rep (
	objsubid int4 NOT NULL,
	objoid int8 NOT NULL,
	description varchar(1000000) NULL,
	db varchar(255) NULL,
	CONSTRAINT pg_description_rep_pkey PRIMARY KEY (objsubid, objoid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_namespace_rep (
	nspowner int8 NULL,
	"oid" int8 NULL,
	db varchar(255) NULL,
	nspname varchar(255) NOT NULL,
	CONSTRAINT pg_namespace_rep_pkey PRIMARY KEY (nspname)
);

CREATE TABLE IF NOT EXISTS jdata.pg_partition_rep (
	parnatts int4 NULL,
	"oid" int8 NOT NULL,
	parrelid int8 NULL,
	db varchar(255) NULL,
	parkind varchar(255) NULL,
	paratts _int4 NULL,
	CONSTRAINT pg_partition_rep_pkey PRIMARY KEY (oid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_partition_rule_rep (
	"oid" int8 NOT NULL,
	parchildrelid int8 NULL,
	paroid int8 NULL,
	db varchar(255) NULL,
	CONSTRAINT pg_partition_rule_rep_pkey PRIMARY KEY (oid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_partitioned_table_rep (
	partnatts int2 NULL,
	partrelid int8 NOT NULL,
	db varchar(255) NULL,
	partstrat varchar(255) NULL,
	partattrs _int4 NULL,
	CONSTRAINT pg_partitioned_table_rep_pkey PRIMARY KEY (partrelid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_sequence_rep (
	seqcache numeric(38, 2) NULL,
	seqcycle bool NULL,
	seqincrement numeric(38, 2) NULL,
	seqmax numeric(38, 2) NULL,
	seqmin numeric(38, 2) NULL,
	seqstart numeric(38, 2) NULL,
	seqrelid int8 NOT NULL,
	db varchar(255) NULL,
	CONSTRAINT pg_sequence_rep_pkey PRIMARY KEY (seqrelid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_type_rep (
	"oid" int8 NOT NULL,
	typnamespace int8 NULL,
	db varchar(255) NULL,
	typname varchar(255) NULL,
	CONSTRAINT pg_type_rep_pkey PRIMARY KEY (oid)
);

CREATE TABLE IF NOT EXISTS jdata.pg_views_rep (
	definition varchar(10000000) NULL,
	db varchar(255) NULL,
	schemaname varchar(255) NOT NULL,
	viewname varchar(255) NOT NULL,
	CONSTRAINT pg_views_rep_pkey PRIMARY KEY (schemaname, viewname)
);

CREATE TABLE IF NOT EXISTS jdata.summary_statistics_rep (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	sum int8 NULL,
	"timestamp" timestamp(6) NULL,
	db varchar(255) NULL,
	"schema" varchar(255) NULL,
	table_name varchar(255) NULL,
	CONSTRAINT summary_statistics_rep_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS jdata.transactions_journal (
	flag bool NULL,
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	response int8 NULL,
	"timestamp" timestamp(6) NULL,
	db varchar(255) NULL,
	message varchar(255) NULL,
	request varchar(255) NULL,
	CONSTRAINT transactions_journal_pkey PRIMARY KEY (id)
);
